### ISSUE TITLE
ROM location undefined

### ISSUE THREAD

**Issue by xapple** [lmmenge/MeSNEmu#24]
So I have MeSNEmu on my iPhone, but nowhere does it say where in the filesystem the ROM files are supposed to be placed. I read all the README. Please advise.

**Comment by aceysmith** [comment]
Maybe it's a little unclear, but it is in the README actually. 

> - Drop your ROMs into the app in iTunes and just run it.

It's set up as a File Sharing app, so if you open iTunes -> iPhone -> Apps section and scroll down, you will see apps listed below that offer that capability. Simply drag and drop (Or use the Add... button) any ROM after selecting MeSNEmu.

**Comment by xapple** [comment]
OK I see, thanks for the quick reply. I'll do that. Out of curiosity, is there a location though on the filesystem where I can just `scp` all the ROMs ? If you have several SNES emulators, you have to use twice the disk space. Usually it's in `/var/mobile/Media`

**Comment by aceysmith** [comment]
I believe it's the Documents directory of the app. Off the top of my head I don't know where on iOS the applications are stored. You could add a command to print that out when the app launches from Xcode, or if you aren't comfortable with the code and have ssh access to your phone, you could add a file through iTunes and `find` on the device for that filename?

**Comment by xapple** [comment]
OK thanks for the advice ! Great app !

**Comment by aceysmith** [comment]
Yeah it's pretty solid, I can't take any credit though. I haven't even made a PR for my fork yet, but maybe someday!

**Comment by xapple** [comment]
I see. I wanted to say, my biggest grudge will all these emulators is always how the directional joystick works. It seems like no one has caught on to the better methods available. Have you tried for instance the Chrono Trigger game as it was ported by Square Enix and sold on the App Store ? Now that's a joystick that brings me joy ! What do you think ?

**Comment by aceysmith** [comment]
Totally agree. My fork fixes the joystick a bit as that was my first gripe too. Haven't tried the official Chromo Trigger port, but that's the ROM I first installed played after installing this app.

**Comment by xapple** [comment]
You should try the official port, it's really worth it. Best joystick to date !
