### ISSUE TITLE
Now It support IOS 11! :D

### ISSUE THREAD

**Issue by Yamilquery** [lmmenge/MeSNEmu#29]
It's incompatible with IOS 11, I try to make this project compatible for the architecture arm64 but I found multiples errors, principally of type "cast int".

- Cast from pointer to smaller type 'pint' (aka 'int') loses information

How can I resolve that?

Thank you!

**Comment by Yamilquery** [comment]
I've added compatibility with IOS 11

https://github.com/Yamilquery/MeSNEmu

Enjoy your self!

**Comment by vichug** [comment]
not to reopen the issue or anything, just saying thanks a lot man it worked for me today :) maybe consider requesting a pull from your branch into original master repo, but no idea if op is still out here/caring about that.
