### ISSUE TITLE
Button Problems

### ISSUE THREAD

**Issue by J7771** [lmmenge/MeSNEmu#3]
Could you fix the buttons? The layout is quite inconvenient (instead of y x, b a, it'd be easier if it was x a, y b) or give us an option to change the layout within the application?
And can you also make it possible to hold more than one button at once (can't run and jump in platformers, or hold an item and jump).

**Comment by carrollc221** [comment]
I understand there is no way to use a single finger for multiple touches, but if you look at the touch functionality of the gba4ios emulator, the handling for that emulator seems to be done a little bit better. You can use the lower of your thumb to get a second button-press in with that emulator, but I think it's based off of actual press-detection, not which finger is being utilized.

Many games require you to use a single-finger technique by using the tip of your thumb for one button press and bending your thumb to get the other button press in.

All games in the Super Mario Brothers series require this technique in later stages - the Donkey Kong Country series, jumping and swallowing at the same time in Yoshi's Island, etc.

Perhaps a alternate solution can be made for this issue? I do believe it's very relevant.

**Comment by carrollc221** [comment]
Also, the snes controller's ABXY buttons are laid out in a diamond fashion. The emulator lays them out like a square. It is very uncomfortable. Perhaps if there is am option to move them around to whatever preference, that would be best suited for anyone's needs.
